### ISSUE TITLE
Addon can produce enormous meta bug lists

### ISSUE THREAD

**Issue by mgaudet** [nbp/meta-bugs#1]
E.g. this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1825267

**Comment by nbp** [comment]
Well the problem is that the list exists in the first place, and that bugzilla API does not offer a way to navigate transitively the closure of blocked bugs.

The code already fetches multiple bugs at a time when possible, we we still have to make at least N request where N is the depth of the tree of blocked bugs.

Thus, this is unavoidable today … not without a change in Bugzilla API, which this addon does not yet have the user base to argue for.
